version: "3.3"

services:
    web:
        container_name: laravel_spa_php
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html/
        ports:
            - 8081:80
        depends_on:
            - mysql_db
    mysql_db:
        container_name: mysql8
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: /br4vu5_root/is
            MYSQL_DATABASE: todo_list
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
        ports:
            - 3307:3306
        volumes:
            - ./docker/mysql_db_data:/var/lib/mysql
            
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin
        restart: always
        ports:
          - 8080:80
        environment:
            PMA_HOST: mysql_db
            PMA_PORT: 3306
        depends_on:
            - mysql_db
    redis:
        container_name: redis_db
        image: redis:latest
        ports: 
            - 6379:6379